name: database-project

services:

  mysql:
    image: mysql:9.6.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./data/database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  mdb-loader:
    build: config/mdb-loader
    container_name: mdb-loader
    platform: linux/amd64
    volumes:
      - ./data/etl/access:${MDB_DIRECTORY}
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MDB_DIRECTORY: ${MDB_DIRECTORY}
    depends_on:
      mysql:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

  webspoon:
    build: config/webspoon
    container_name: webspoon
    platform: linux/amd64
    ports:
      - "8085:8080"
    volumes:
      - ./data/etl:/etl
      - ./data/etl/access:/access
      - ./data/etl/lib:/usr/share/webspoon/kettle/plugins/databases
      - ./data/etl/lib:/data-integration/lib/ext

  pdi:
    image: zhicwu/pdi-ce:8.0
    container_name: pdi
    platform: linux/amd64
    ports:
      - "8082:8080"
    volumes:
      - ./data/tl/data:/data
      - ./data/etl/access:/access
      - ./data/etl/lib:/data-integration/lib/ext

  pentaho-server:
    image: oliveiha/pentaho-server:9.4.7_openjdk8
    container_name: pentaho-server
    platform: linux/amd64
    ports:
      - "8083:8080"
    depends_on:
      - mysql

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "8084:3000"